### ISSUE TITLE
HDFS log dataset

### ISSUE THREAD

**Issue by mannnnntheng** [LogIntelligence/LogADEmpirical#2]
Do you use the same HDFS log dataset as in DeepLog paper? Could you please provide the log dataset? Or anywhere can I view the logs?

**Comment by LogIntelligence** [comment]
We use a public HDFS dataset from [Loghub](https://github.com/logpai/loghub). The detail of the HDFS dataset can be found [here](https://github.com/logpai/loghub/tree/master/HDFS#hdfs_1). For the raw dataset, you can download from [Zenodo](https://zenodo.org/record/3227177#.YmHxSvNByrM) ([HDFS_1](https://zenodo.org/record/3227177/files/HDFS_1.tar.gz) dataset).

Thanks

**Comment by mannnnntheng** [comment]
Thank you for your quick response!
