### ISSUE TITLE
Confusion about log parsing

### ISSUE THREAD

**Issue by yzbrlan** [LogIntelligence/LogADEmpirical#4]
I have a confusion about how to set parameters for parsing.I tried to parse HDFS with the settings in the figure, but there was obviously a problem. What is the right way?
There are four data sources. How should we set the parameters for parsing?
<img width="961" alt="截屏2022-04-25 15 55 03" src="https://user-images.githubusercontent.com/22017571/165044978-c11e316c-a828-484c-a389-e1a6d47dbb7a.png">

**Comment by vanhoanglepsa** [comment]
Hi,
We use log parser from [LogPAI](https://github.com/logpai/logparser). We haven't included the log parser in our repository yet. You can refer to [Drain](https://github.com/logpai/logparser/blob/master/benchmark/Drain_benchmark.py) parser to check the set of parameters for parsing. We used the same parameters from LogPAI for our study.

Thanks
